# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20170407_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='fichierEnonce',
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='fichierTest',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='enonce',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='test',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='code',
            name='idEpreuve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Epreuve'),
        ),
        migrations.AddField(
            model_name='code',
            name='idEtudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Etudiant'),
        ),
    ]
