# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20170409_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
