# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20170409_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='score',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='numero',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='points',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='score',
            field=models.IntegerField(default='0'),
        ),
    ]
