# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20170409_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='idEpreuve',
            new_name='epreuve',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='idEtudiant',
            new_name='etudiant',
        ),
    ]
