# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_etudiant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='nom',
        ),
    ]
