# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20170409_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='titre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
