# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_epreuve_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='difficulte',
            field=models.IntegerField(default=0),
        ),
    ]
