# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_epreuve_difficulte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epreuve',
            name='numero',
        ),
    ]
