# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_remove_epreuve_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='estClasse',
            field=models.BooleanField(default=True),
        ),
    ]
