# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_etudiant_estclasse'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='epreuve',
            order_with_respect_to='difficulte',
        ),
    ]
