# Generated by Django 2.2.4 on 2019-08-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_auto_20190827_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='estDoublePrenom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.IntegerField(choices=[(0, 'CPGE 1'), (1, 'CPGE 2'), (2, 'Anciens'), (3, 'Profs'), (4, 'Autre')], default=0),
        ),
    ]
